// Code generated by go-swagger; DO NOT EDIT.

package greetings

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GreetByNameOKCode is the HTTP code returned for type GreetByNameOK
const GreetByNameOKCode int = 200

/*GreetByNameOK A success response with the user's greeting

swagger:response greetByNameOK
*/
type GreetByNameOK struct {

	/*
	  In: Body
	*/
	Payload *GreetByNameOKBody `json:"body,omitempty"`
}

// NewGreetByNameOK creates GreetByNameOK with default headers values
func NewGreetByNameOK() *GreetByNameOK {

	return &GreetByNameOK{}
}

// WithPayload adds the payload to the greet by name o k response
func (o *GreetByNameOK) WithPayload(payload *GreetByNameOKBody) *GreetByNameOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the greet by name o k response
func (o *GreetByNameOK) SetPayload(payload *GreetByNameOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GreetByNameOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GreetByNameBadRequestCode is the HTTP code returned for type GreetByNameBadRequest
const GreetByNameBadRequestCode int = 400

/*GreetByNameBadRequest An error response indicating the user does not exist

swagger:response greetByNameBadRequest
*/
type GreetByNameBadRequest struct {

	/*
	  In: Body
	*/
	Payload *GreetByNameBadRequestBody `json:"body,omitempty"`
}

// NewGreetByNameBadRequest creates GreetByNameBadRequest with default headers values
func NewGreetByNameBadRequest() *GreetByNameBadRequest {

	return &GreetByNameBadRequest{}
}

// WithPayload adds the payload to the greet by name bad request response
func (o *GreetByNameBadRequest) WithPayload(payload *GreetByNameBadRequestBody) *GreetByNameBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the greet by name bad request response
func (o *GreetByNameBadRequest) SetPayload(payload *GreetByNameBadRequestBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GreetByNameBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GreetByNameInternalServerErrorCode is the HTTP code returned for type GreetByNameInternalServerError
const GreetByNameInternalServerErrorCode int = 500

/*GreetByNameInternalServerError Internal server error

swagger:response greetByNameInternalServerError
*/
type GreetByNameInternalServerError struct {
}

// NewGreetByNameInternalServerError creates GreetByNameInternalServerError with default headers values
func NewGreetByNameInternalServerError() *GreetByNameInternalServerError {

	return &GreetByNameInternalServerError{}
}

// WriteResponse to the client
func (o *GreetByNameInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(500)
}
