// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "Server",
    "version": "0.1.0"
  },
  "basePath": "/api/v1",
  "paths": {
    "/greetings/{name}": {
      "get": {
        "tags": [
          "greetings"
        ],
        "operationId": "greetByName",
        "parameters": [
          {
            "minLength": 1,
            "type": "string",
            "description": "The name of the user to be greeted",
            "name": "name",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "A success response with the user's greeting",
            "schema": {
              "type": "object",
              "required": [
                "greeting"
              ],
              "properties": {
                "greeting": {
                  "description": "The greeting given to the user",
                  "type": "string",
                  "minLength": 1,
                  "x-nullable": false
                }
              }
            }
          },
          "400": {
            "description": "An error response indicating the user does not exist",
            "schema": {
              "type": "object",
              "required": [
                "reason"
              ],
              "properties": {
                "description": {
                  "description": "An optional detailed description of the error",
                  "type": "string",
                  "minLength": 1,
                  "x-nullable": false
                },
                "reason": {
                  "description": "A brief description of the error",
                  "type": "string",
                  "minLength": 1,
                  "x-nullable": false
                }
              }
            }
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "title": "Server",
    "version": "0.1.0"
  },
  "basePath": "/api/v1",
  "paths": {
    "/greetings/{name}": {
      "get": {
        "tags": [
          "greetings"
        ],
        "operationId": "greetByName",
        "parameters": [
          {
            "minLength": 1,
            "type": "string",
            "description": "The name of the user to be greeted",
            "name": "name",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "A success response with the user's greeting",
            "schema": {
              "type": "object",
              "required": [
                "greeting"
              ],
              "properties": {
                "greeting": {
                  "description": "The greeting given to the user",
                  "type": "string",
                  "minLength": 1,
                  "x-nullable": false
                }
              }
            }
          },
          "400": {
            "description": "An error response indicating the user does not exist",
            "schema": {
              "type": "object",
              "required": [
                "reason"
              ],
              "properties": {
                "description": {
                  "description": "An optional detailed description of the error",
                  "type": "string",
                  "minLength": 1,
                  "x-nullable": false
                },
                "reason": {
                  "description": "A brief description of the error",
                  "type": "string",
                  "minLength": 1,
                  "x-nullable": false
                }
              }
            }
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    }
  }
}`))
}
